### ISSUE TITLE
Game Token is big problem GF Update

### ISSUE THREAD

**Issue by Nypz** [hatz02/GflessClient#1]
The code block created in auth/iovation and sent to auth/thin/codes to enter the game is created from https://gameforge.com/tra/game1.js and is checked and changed every time you log in. Fiddler, I got these results. How can we solve this problem, there is no protection for now but when they are active it will be a big problem. When the code is not generated, the server returns message: 'Not allowed to create code'

**Comment by hatz02** [comment]
Hi, the request to auth/iovation is not needed at all to log in that's why i'm not sending it. Gfless client works correctly and if you're interested in doing something similar you should check the sources I used to make it which explains very deeply all you need to know: 

https://github.com/morsisko/NosTale-Auth 
https://github.com/morsisko/NosTale-Gfless

**Comment by Nypz** [comment]
I came across this while listening to the Gameforge client. There is no need for such a scenario for Nostale at the moment, but it sends these codes when entering. It has come to my attention that this system may be active in the near future, I'm investigating what could happen in this scenario. I'll look into the sources, thanks
