### ISSUE TITLE
Does this also work with Metin2?

### ISSUE THREAD

**Issue by Heggeg** [hatz02/GflessClient#6]
Does this also work with Metin2?

**Comment by hatz02** [comment]
As it is right now no, it doesn't, it works for Nostale but the login protocol for Metin2 might be similar

**Comment by SoNiice** [comment]
> As it is right now no, it doesn't, it works for Nostale but the login protocol for Metin2 might be similar

I actually made it work for Metin2 in the past and just did with newest version you released, thanks for your effort logging and decrypting all the GF data. Sadly I didn't find any way to contact you externally so I will just ask you something here. Do you know if the blackbox token actually does change at some point or can we simply use it permanently? Metin2 is known for blocking you in the GFClient with a red bar notification without any specific reason sometimes. Does this happen with Nostale as well?

**Comment by hatz02** [comment]
> 

Some fields in the identity are updated everytime a new blackbox is generated: [https://github.com/hatz02/GflessClient/blob/ca97e9c97750d80b275df89cdd0159bea88222e4/Launcher/src/auth/identity.cpp#L14](url). As you can see each time a blackbox is generated I update those parameters so that the new blackbox is not the same as the last one: [https://github.com/hatz02/GflessClient/blob/ca97e9c97750d80b275df89cdd0159bea88222e4/Launcher/src/auth/nostaleauth.cpp#L95](url).

About the red bar it happens with nostale aswell but it is not frequent, you only get it if you do a lot of incorrect logins or when the SSL certificate of the client expires.

**Comment by SoNiice** [comment]
I see, so you only update some data with every login, but other than that it's fine?

**Comment by hatz02** [comment]
> I see, so you only update some data with every login, but other than that it's fine?

yes

**Comment by SoNiice** [comment]
@hatz02 I'm sorry I have to bother you again, but I got another question I'm currently struggling with. Gameforge games do use a named pipe ("GameforgeClientJSONRPC") to communicate with the GFClient, how do I differ between different clients so I don't login the same account on all clients? Is there a way to get the process connecting to the pipe I do not know about or do I really have to have perfect timings so different clients do not interfer with others using the pipe simultaneously? Couldn't really figure out how the GFClient is handling this with checking the processes and the pipe while using the original client. Since I can simply open multiple clients with the GFClient, press login the same time on all of 'em and they will login correctly :|

**Comment by Abraam1997** [comment]
> > As it is right now no, it doesn't, it works for Nostale but the login protocol for Metin2 might be similar
> 
> I actually made it work for Metin2 in the past and just did with newest version you released, thanks for your effort logging and decrypting all the GF data. Sadly I didn't find any way to contact you externally so I will just ask you something here. Do you know if the blackbox token actually does change at some point or can we simply use it permanently? Metin2 is known for blocking you in the GFClient with a red bar notification without any specific reason sometimes. Does this happen with Nostale as well?

Can you share it please,  I tried to made it for metin2, but I failed.
